# https://docs.codeclimate.com/docs/default-analysis-configuration
# https://docs.codeclimate.com/docs/advanced-configuration

version: '2' # required to adjust maintainability checks
checks:
  complex-logic:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 8
  method-lines:
    config:
      threshold: 40

exclude_patterns:
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - 'Tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  - '**/@types/'
  - '**/interfaces/'
  - '**/_types.*'
  - '**/*.stories.*'
  - '**/*.test.*'
  - '.storybook/'
  - 'tests/'
  - 'coverage/'
  - '.next/'
  - '.swc/'
